### ISSUE TITLE
can't compile in typst version 0.12.0 (latest as of writting)

### ISSUE THREAD

**Issue by mtoons** [catppuccin/typst#28]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### What version(s) of the Typst compiler are you using?

0.12.0

### What version(s) of the Catppuccin package for Typst are you using?

https://github.com/catppuccin/typst/commit/090107df4cdf39b4cc8809cc4e810f69f8d72ac7

### Describe your problem.

When trying to compile a simple typst document (here `hello.typ` I get a compilation error coming from the package :
```sh
$ typst compile hello.typ
```
```sh
can only be used when context is known
   ┌─ @local/catppuccin:0.1.0\src\catppuccin.typ:90:19
   │
90 │     default: it => measure(it).width + 1cm,
   │                    ^^^^^^^^^^^
   │
   = hint: try wrapping this in a `context` expression
   = hint: the `context` expression should wrap everything that depends on this function

help: error occurred in this function call
    ┌─ @local/catppuccin:0.1.0\src\catppuccin.typ:115:29
    │
115 │       config.insert("width", (config.at("width"))(it))
    │                              ^^^^^^^^^^^^^^^^^^^^^^^^
```

### What platform(s) are you seeing the problem on?

cli

**Comment by TimeTravelPenguin** [comment]
Could you please provide either a demo or your `hello.typ` example?

**Comment by TimeTravelPenguin** [comment]
Ah, I think I see the issue. Not sure how that crept in there.

Code blocks and stuff will be changed in a future version, but I will look into a simple fix for now

**Comment by mtoons** [comment]
Thanks a lot! The init file is generating this error.
